### ISSUE TITLE
Support parsing imported build files.

### ISSUE THREAD

**Issue by motobud31** [NickHeap2/vscode-ant#1]
I have a "build.xml" in my root directory that contains the line:
`   <import file="common.xml"/>`
but in the "Ant Target Runner" window, only the targets in the "build.xml" file are shown and not targets in the "common.xml" file.

**Comment by NickHeap2** [comment]
First thing to change is to allow different build file names then that’s actually on my list of things to do to change the way the targets are parsed.
Will update you when I get it done.
Cheers

**Comment by bm-stschneider** [comment]
Having the same issue with even a fileset of imports

**Comment by foobarlab** [comment]
Would be great to have this feature! In my case I have imports at more than one level, so there is even an import on an imported file.

**Comment by NickHeap2** [comment]
Big work project just ending so hoping to get back on this!

**Comment by NickHeap2** [comment]
I have the parsing, displaying and running working for this now. I just need to work on how to highlight imports in the ui and get reveal definition working correctly.

**Comment by TonyGravagno** [comment]
Looking forward to this feature. Thanks.

**Comment by NickHeap2** [comment]
As usual paid work has got in the way but this is WIP atm on the multi-level branch.

**Comment by NickHeap2** [comment]
Super late but this is now released.

**Comment by bm-stschneider** [comment]
Better late than never.

**Comment by NickHeap2** [comment]
Closing now that this is complete.
