### ISSUE TITLE
unable to update to 0.2.0 release

### ISSUE THREAD

**Issue by acid-srvnn** [NickHeap2/vscode-ant#12]
0.2.0 release is not showing in vs code

**Comment by NickHeap2** [comment]
Hi I'm just clearing up some remaining things I'm not happy with then I will be releasing 0.2.0. Should probably be today or tomorrow.

**Comment by NickHeap2** [comment]
I've now released 0.2.1 (I messed up the README including)

**Comment by NickHeap2** [comment]
I'm going to close this now as nothing further to do.
