### ISSUE TITLE
builds not showing up in VSC 1.47.1

### ISSUE THREAD

**Issue by martin242m** [NickHeap2/vscode-ant#13]
After Updating to VSC 1.47.1 no builds are showing up in the Ant Target Runner. The Problem occured after the update. 
Ant Version is  1.10.8. Also tried with 1.10.6

**Comment by NickHeap2** [comment]
I've just done the update myself and not found any problems with any of my projects.Can you give me a way to reproduce?

**Comment by martin242m** [comment]
I'll try my best to give you my settings:
Win10 with ant path C:\apache-ant-1.10.8
In VSC:
build.evn is empty
build.xml contains the script. I just tried a really simple one:
`<project name="CAP_m.cap">
    <target name="buildfile" depends="buildwar_m.CAP"></target>
</project>`
Both files are in root in the explorer

Extension settings:
![Anmerkung 2020-07-17 080826](https://user-images.githubusercontent.com/52254858/87754227-b9bfca80-c804-11ea-9527-f26108da4969.jpg)

Until May 2020 everything was fine. After the June 2020 Update the Ant Target Runner stays empty.
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Can I supply any further information? Still not sure if its just me..

**Comment by NickHeap2** [comment]
@martin242m Sorry for the delayed response but I did try those exact settings and didn't get the issue myself.
Are you still getting this problem with the 1.48.0 version?
![image](https://user-images.githubusercontent.com/42422453/90379127-364b0080-e072-11ea-9b69-97c24c9f5033.png)
![image](https://user-images.githubusercontent.com/42422453/90379276-6d211680-e072-11ea-98b4-7826a6c5209f.png)

**Comment by martin242m** [comment]
Hey Nick, also sorry for the late response. I just checked your new Version  with VSC 1.48.2. Somehow the Issue seems to be resolved. Everything seems to work as normal as far as I can tell.
Thank you for your help :)
