### ISSUE TITLE
Plugin not loading on VsCode Version 1.30.0 (1.30.0)

### ISSUE THREAD

**Issue by jefersonchaves** [NickHeap2/vscode-ant#2]
Seems that plugin stopped to load after I upgraded VsCode in MacOS Mojave. I loved the plugin but need some assistance to load it again.

**Comment by NickHeap2** [comment]
Hey @jefersonchaves sorry I've only just seen this. Does it still not work on the latest Mac version? I'm happy to get it working again if you can provide me with error details.

**Comment by jefersonchaves** [comment]
Hey @NickHeap2: no worries, thanks again. Now it is not even refreshing the targets (but might because I moved to Azul Zulu JVM due to recent Oracle changes).
