### ISSUE TITLE
Set-Location (cd) fails if path contains a space

### ISSUE THREAD

**Issue by AureliusSlawinski** [NickHeap2/vscode-ant#20]
My workspace path contains a space ("E:\Work Flex\...").

This is no problem as long I open a folder in VSC, but with workspaces, the command "cd e:\Work Flex\..." fails (if current directory is a different once).

And causes an error when running build.xml:
Unable to locate tools.jar. Expected to find it in C:\Program Files (x86)\Java\jre1.8.0_271\lib\tools.jar
Build failed

Would this be hard to fix?

Thanks and regards.

**Comment by sflynn850** [comment]
If you wrap the path in quotes there's a decent chance of it working.

-Sean

**Comment by AureliusSlawinski** [comment]
Yes, if I enter cd "e:\Work Flex..." in quotes manually into the terminal window before running build.xml, there is no error.

**Comment by NickHeap2** [comment]
@AureliusSlawinski This is resolved in 0.3.1.

**Comment by NickHeap2** [comment]
Closing as fix has been out more than a year.
