### ISSUE TITLE
How do I setup this plugin to execute Ant script?

### ISSUE THREAD

**Issue by Patlatus** [NickHeap2/vscode-ant#3]
I previously used Force.com eclipse plugin or Illuminated Cloud or jetforcer plugins for Intellij Idea where I was able to run Ant targets successfully.

I am looking for a way to run Ant target in Visual Code, and trying to use this plugin, but I receive some very basic failure 

> > ant "0. Prepare for deploy"
> ant : The term 'ant' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
> path was included, verify that the path is correct and try again.
> At line:1 char:1
> + ant "0. Prepare for deploy"
> + ~~~
>     + CategoryInfo          : ObjectNotFound: (ant:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

How do I fix this problem?

**Comment by Patlatus** [comment]
![image](https://user-images.githubusercontent.com/1489026/54753549-fae0a400-4be9-11e9-8ab2-dd4d1f812cb2.png)

**Comment by NickHeap2** [comment]
Hope you managed to resolve this. It won't work with defaults unless ant is in your PATH. If it isn't then you need to set the ant.executable setting to tell it where the ant executable is. You may also need to set ant.home to tell it where your ant folder is. Example settings would be ant.executable: C:\ant\bin\ant.bat & ant.home: C:\ant

**Comment by Patlatus** [comment]
Hi @NickHeap2 I wasn't able to resolve this and I don't have C;\Ant\bin\ant.bat. When I use Eclipse or Illuminated Cloud I do not install Ant additionally since it is included into Eclipse or Illuminated Cloud application bundle, does this mean I have to install Ant separately and set the link to installation folder somewhere?

**Comment by NickHeap2** [comment]
@Patlatus It doesn't bundle ant with it atm but I'll look into that for the upcoming release. Yes that's correct you can just install ant yourself and then set the settings to point at that installation.

**Comment by Patlatus** [comment]
Is there any documentation or specification where I can possibly read about how to configure settings to point at that installation?

**Comment by NickHeap2** [comment]
That sounds like a good idea :)
I'll see if I can get some done over the weekend.

**Comment by NickHeap2** [comment]
Well work life got in the way but the extension now bundles ant.

**Comment by NickHeap2** [comment]
Closing this now that there are no more comments.
