### ISSUE TITLE
'Run selected target' double quoting target with space

### ISSUE THREAD

**Issue by stefandrissen** [NickHeap2/vscode-ant#32]
When I use the 'Run selected target' icon and my target contains a space:
````
ant ""all b-dos""

BUILD FAILED
Target "all" does not exist in the project
````
If I use the 'Run Ant Target' context menu on the target, it is executed correctly:
````
ant "all b-dos"
````
Work-around: remove spaces from Ant build targets.

Environment: 
- Windows 10
- PSVersion 5.1.19041.1320

**Comment by NickHeap2** [comment]
Replicated
![image](https://user-images.githubusercontent.com/42422453/141660364-e6927709-bfc3-4b8f-9f15-d132f8b7e438.png)

**Comment by stefandrissen** [comment]
No longer an issue.
