### ISSUE TITLE
Ant target with parentheses fails

### ISSUE THREAD

**Issue by stefandrissen** [NickHeap2/vscode-ant#33]
While replacing the space in my targets with a hyphen (for #32), I also restored the parentheses in my targets. Now both 'Run Ant Target' and 'Run Selected Ant Target' fail:
````
ant all-(b-dos)
b-dos : The term 'b-dos' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
````
Work-around: remove parentheses from target.

The work-arounds for this issue and #32 are more than adequate for me. When moving from another environment (Eclipse in my case) these errors when just getting started can be a bit daunting.

**Comment by NickHeap2** [comment]
Replicated
![image](https://user-images.githubusercontent.com/42422453/141660277-ff14ee8b-7ef0-4862-9dde-4efbbc1df060.png)

**Comment by joellutz** [comment]
This may be related to this:
Parsing this
```
<project  name="Test" default="" basedir="." >

	<target name="Init" >
		<echo message="Init" />
	</target>

	<target name="A (b)"  depends="Init" >
		<echo message="Test" />
	</target>

</project>
```
 fails with the error 

> ATR: Error reading build.xml! TypeError: Cannot set properties of undefined (setting 'depends')

It will parse just fine when doing one of the following:
- renaming the target to `name="a (b)"` (lowercase)
- renaming the target to `name="A b"` (no brackets)
- removing the `depends="Init"`

Any ideas on why this behaviour occurs?

PS: I really like the new error messages! Only with them I was able to pinpoint this problem.

**Comment by NickHeap2** [comment]
Good catch @joellutz it turns out to be that I needed to escape the target name before doing a regexp match on it.
Will release an update to fix this.

**Comment by NickHeap2** [comment]
@stefandrissen this issue should now be fixed in the latest version.
