### ISSUE TITLE
Quotes are not supplied for targets with spaces anymore

### ISSUE THREAD

**Issue by daumling** [NickHeap2/vscode-ant#4]
The last change apparently broke the quotes around ant targets. I have several targets with spaces, like "www Post Minifieds". These targets do not receive quotes anymore.

Should be: ant "www Post Minifieds"
is: ant www Post Minifieds

**Comment by NickHeap2** [comment]
Manually run targets are still working for me.
For auto targets you need to escape quote the targets like the example:
    {
      "filePattern": "**/*.spacetest",
      "runTargets": "\"space test\" test",
      "initialDelayMs": 2000
    }

**Comment by NickHeap2** [comment]
I'm assuming this is ok now. Will close in a couple of days.

**Comment by NickHeap2** [comment]
Ok closing now as no further comments.
