### ISSUE TITLE
Extension nickheap.vscode-ant has provided an invalid tree item

### ISSUE THREAD

**Issue by stefandrissen** [NickHeap2/vscode-ant#41]
Not sure if this is a VS Code issue or an extension issue (using 0.3.3)

As of [VS Code 1.7.2](https://code.visualstudio.com/updates/v1_72), refreshing the Ant Targets results in an error and the Ant targets that can be launched are not shown in the side bar:

``Extension nickheap.vscode-ant has provided an invalid tree item.``

If I revert to [VS Code 1.7.1](https://code.visualstudio.com/updates/v1_71) the problem is gone.

**Comment by AureliusSlawinski** [comment]
Same for me. I also downgraded VS Code version.

**Comment by NickHeap2** [comment]
@stefandrissen thanks for letting me know I'll take a look at this today and try to get things working. I can then amke a release with the new build file parsing turned on by default.

**Comment by NickHeap2** [comment]
Looks like the root TreeItem is failing for having a command property of '' when it now needs to be undefined.

**Comment by NickHeap2** [comment]
Fix is incoming.

**Comment by NickHeap2** [comment]
@stefandrissen @AureliusSlawinski This is now fixed in the latest 0.4.0 release.

**Comment by stefandrissen** [comment]
Thanks for the quick fix!
