### ISSUE TITLE
Permission denied to ant executable

### ISSUE THREAD

**Issue by encodis** [NickHeap2/vscode-ant#44]
Hi

Following the patch (0.4.0) for the tree view error (and thanks for the quick response!) I now get:

ATR: Error reading build.xml! Error: /bin/sh: /Users/phil/.vscode/extensions/nickheap.vscode-ant-0.4.0/dist/apache-ant/bin/ant: Permission denied

I've reinstalled the extension and restarted VSCode itself. I also tried setting the executable flag on ant and antRun (they were not set) but this didn't help. Neither did un-setting the "Use Ant for Parsing" option. This is on macOS 12.6, VSCode v1.72

Thanks!

**Comment by NickHeap2** [comment]
@encodis Thanks for letting me know. Did you try un-setting the use ant for parsing and then restart VSCode?
Second thing to try is installing your own version of Ant outside of VSCode and then set the ant.home and ant.executable settings.
I may have to change to publishing from Linux to make sure the permission flags get preserved for Ant.

**Comment by NickHeap2** [comment]
Have just replicated on wsl.

**Comment by NickHeap2** [comment]
Can confirm:
Changing to not use ant to parse then restarting works fine. I'll get that fixed tomorrow.
Using an external ant install works fine. On wsl I set ant.home to /usr/share/ant and everything then works fine.

**Comment by encodis** [comment]
Hi

I did try an external ant install (/usr/local/bin/ant via homebrew) and it did work on some projects but others seem to get stuck at the "loading build.xml" stage - the progress bar on the ATR outline sections just goes back and forth for ever - but it doesn't error outright. Suggested fix does work for me so thanks for the tip!

**Comment by NickHeap2** [comment]
@encodis Are you able to share the build file of a project where it fails?

**Comment by encodis** [comment]
This was one of them

https://github.com/encodis/xpants/blob/master/build.xml

However, it does work now with the "uncheck and restart" trick!

**Comment by NickHeap2** [comment]
@encodis I've just released 0.4.1 that now works for me with the ant parser on wsl.

**Comment by encodis** [comment]
@NickHeap2 seems to be working ok now. Thanks for the quick response - I use this in a lot of projects!

**Comment by NickHeap2** [comment]
@encodis Great news. I've tried the xpants build.xml and can see there is an issue there with the ant parsing not resolving. Will close this issue down and raise that as a new one.
