### ISSUE TITLE
Autobuild caused by filename

### ISSUE THREAD

**Issue by mikefechner** [NickHeap2/vscode-ant#52]
Using the autobuild feature of this fantastic plugin, is there any way how I can pass the name of the file that caused the autobuild to the ANT script? 

We use this with our Eclipse ANT builders and want to migrate this to VS Code now.

**Comment by NickHeap2** [comment]
Hey @mikefechner, I don't often use OpenEdge now so am not actively developing this extension at the moment. Am happy to add this change in for you though as I need to bump some dependencies anyway.

**Comment by NickHeap2** [comment]
@mikefechner this change is now in version 0.5.0 and passes in the triggering filename as autoTargetTriggerFilename.
Let me know if that works for you.

**Comment by mikefechner** [comment]
Works like charme :) Thanks!
